apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: ${ACR}/product_service:${TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_HOST
              value: product-db-service
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: ecomm-config
                  key: PRODUCTS_DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ecomm-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecomm-secrets
                  key: POSTGRES_PASSWORD
            - name: AZURE_STORAGE_ACCOUNT_NAME
              valueFrom:
                secretKeyRef:
                  name: ecomm-secrets # Secret name matches
                  key: AZURE_STORAGE_ACCOUNT_NAME
            - name: AZURE_STORAGE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: ecomm-secrets # Secret name matches
                  key: AZURE_STORAGE_ACCOUNT_KEY
            - name: AZURE_STORAGE_CONTAINER_NAME
              valueFrom:
                configMapKeyRef:
                  name: ecomm-config # ConfigMap name matches
                  key: STORAGE_CONTAINER_NAME
            - name: AZURE_SAS_TOKEN_EXPIRY_HOURS
              valueFrom:
                configMapKeyRef:
                  name: ecomm-config # ConfigMap name matches
                  key: SAS_TOKEN_EXPIRY_HOURS
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: ${NAMESPACE}
spec:
  selector:
    app: product-service
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer
